pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("maven2"){
            steps{
            sh 'mvn clean validate compile install test package '
        }
    }
      stage('upload artifact'){
        steps{
            sh curl -uadmin:AP5CNW3E6mvDGwoPRSb2crkLwR2 -T  \
            target/bio*.jar \
            "http://ec2-52-91-127-132.compute-1..amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"
        }
        }
        }
        }

