pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
     stage('sonar-scan'){
        steps{
             withSonarQubeEnv('sonarQube'){
             sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=alexrukund_practice-geo'
             }
        }
     }
    }
    stages{
        stage("maven2"){
            steps{
            sh 'mvn clean validate compile install test package '
        }
    }
      stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP5CNW3E6mvDGwoPRSb2crkLwR2 -T \
             target/bio*.jar "http://ec2-52-91-127-132.compute-1.amazonaws.com:8081/artifactory/geosolution/geo/bio_${BUILD_ID}.jar"'
        }
        }
        }

}